export const DATA = {
  LOAD: "DATA_LOAD",
  LOAD_SUCCESS: "DATA_LOAD_SUCCESS",
  LOAD_FAIL: "DATA_LOAD_FAIL"
};

export const SEARCH_RESULT = {
  LOAD: "SEARCH_RESULT_DATA_LOAD",
  LOAD_SUCCESS: "SEARCH_RESULT_DATA_LOAD_SUCCESS",
  LOAD_FAIL: "SEARCH_RESULT_DATA_LOAD_FAIL",
  NO_RESULT_ERROR: "SEARCH_RESULT_NO_RESULT_ERROR"
};

export const SET_KEYWORD = "SET_KEYWORD";
